version: '3.8'

services:
  # ---------------------------
  # Zookeeper
  # ---------------------------
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.10
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  # ---------------------------
  # Kafka Broker
  # ---------------------------
  kafka:
    image: confluentinc/cp-kafka:7.2.10
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    depends_on:
      - zookeeper

  # ---------------------------
  # Flink JobManager
  # ---------------------------
  jobmanager:
    image: flink:1.16.3
    container_name: flink-jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    volumes:
      - ./docker/lib/flink-jobs:/opt/flink/usrlib
    depends_on:
      - kafka

  # ---------------------------
  # Flink TaskManager
  # ---------------------------
  taskmanager:
    image: flink:1.16.3
    container_name: flink-taskmanager
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    scale: 1
    volumes:
      - ./docker/lib/flink-tasks:/opt/flink/usrlib
    depends_on:
      - jobmanager

  # ---------------------------
  # ClickHouse
  # ---------------------------
  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    container_name: clickhouse
    ports:
      - "8123:8123"   # HTTP interface for queries
      - "9000:9000"   # Native TCP interface
    volumes:
      - ./data/clickhouse:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  # ---------------------------
  # Grafana
  # ---------------------------
  grafana:
    image: grafana/grafana:10.0.0
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - clickhouse
    environment:
      GF_INSTALL_PLUGINS: vertamedia-clickhouse-datasource

